### ISSUE TITLE
xeft-full-reindex: Xapian library error: "DatabaseCorruptError: Expected block 76 to be level 1, not 0"

### ISSUE THREAD

**Issue by 404cn** [casouri/xeft#10]
How to reproduce:

Here is the config:
```elisp
;;; -*- lexical-binding: t -*-

(setq straight-check-for-modifications '(check-on-save find-when-checking))
(setq straight-vc-git-default-clone-depth 1)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package '(xeft
                        :type git :host github :repo "casouri/xeft"
                        :pre-build ("make")
                        :files (:defaults "Makefile" "*.h" "*.cc" "*.so")))

(setq xeft-directory "~/Dropbox/org/roam"
      xeft-database "~/Dropbox/org/roam/db")

```

And **M-x xeft**, then get this error message in minibuffer.

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H1715)) of 2022-03-03 (Install from brew install emacs-app-good)
OS: macOS 12.3

Do I need to check anything else like xapian?

**Comment by casouri** [comment]
As the error message said, the xapian database is corrupted. A quick fix is to delete the database ("~/Dropbox/org/roam/db"), and xeft will recreate a new one automatically. Why is the database corrupted in the first place is hard to tell. Maybe dropbox corrupted it when syncing? I would move the database out of dropbox as there is no point syncing the database anyway.

**Comment by 404cn** [comment]
> A quick fix is to delete the database ("~/Dropbox/org/roam/db"), and xeft will recreate a new one automatically.

Thanks it works :)
