### ISSUE TITLE
Add MS-Windows support ?

### ISSUE THREAD

**Issue by pRot0ta1p** [casouri/xeft#11]
For ms-windows I tried using msys2 to compile the module , and it turns out not hard to do.

All I need todo is first install package  mingw-w64-x86_64-xapian-core and change the `xapian-lite.so` to `xapian-lite.dll` in Makefile.

Can you change the Makefile so it produce a .dll file in ms-windows instead of a .so file? This and the msys2 dependency is all it need to make xeft work on windows.

**Comment by casouri** [comment]
Thanks. I modified Makefile and it should produce dll on windows now, could you verify?

**Comment by pRot0ta1p** [comment]
Yes it works , thank you ! 👍

**Comment by pRot0ta1p** [comment]
I use emacs inside msys2, but I think the promlem is with the Makefile, try apply this patch to Makefile and make sure the compiled .dll file is inside your `load-path` , when asked about `make PREFIX` input nothing so the compiled .dll file will be at the same directory as xeft.el.

````diff
diff --git a/Makefile b/Makefile
index d890d78..c627f5d 100644
--- a/Makefile
+++ b/Makefile
@@ -7,17 +7,17 @@ LDFLAGS=-L$(PREFIX)/lib
 LDLIBS=-lxapian
 
 # Dylib extensions.
-ifeq ($(OS),Windows_NT)
-	SOEXT = dll
-endif
 ifeq ($(shell uname),Darwin)
 	SOEXT = dylib
 else
 	SOEXT = so
 endif
+ifeq ($(OS),Windows_NT)
+	SOEXT = dll
+endif
 
 xapian-lite.$(SOEXT): module/xapian-lite.cc
 	$(CXX) $< -o $@ -shared $(CXXFLAGS) $(LDFLAGS) $(LDLIBS)
 
 clean:
-	rm -f *.so *.o
+	rm -f *.so *.o *.dll
````

**Comment by casouri** [comment]
Hmmm, could you explain what does this change fix?

**Comment by pRot0ta1p** [comment]
The goal is to produce a dll file on windows, the catch with msys2 is that it is also a unix environment, so 
```makefile
 ifeq ($(shell uname),Darwin)
 	SOEXT = dylib
 else
 	SOEXT = so
 endif
````
will cause SOEXT = so in msys2, this will compile a xapian-lite.so without error but emacs in mingw64 is a native win64 application ( the official win distribution of emacs is compiled with mingw64 toolchain) and only recognize the native dll file, so to fix this, I moved the ifeq Windows_NT part behind so SOEXT will be dll.

**Comment by mcrosson** [comment]
@pRot0ta1p Thank you for the clarity. I had come up with a similar process but I'm getting an error on GPL compatibility.

@casouri The patch will fixup the build for msys2 so the dll is properly generated and found by emacs when loading xeft.

**For both of y'all:** I'm getting a gpl compatibility error (below) when loading `xeft` inside msys2 or with the native windows build of emacs. I'm not sure if its because I didn't pull the 11.x g++ or not and I'm 100% not sure how to get msys2 to install concurrent versions of g++ so I can use an older version.

**The error**: `Module is not GPL compatible: "/home/kemonine/.emacs.d/xeft/xapian-lite.dll`

**Full build process**:

 ```sh
export PATH=/mingw64/bin/:${PATH} # setup g++ binary discovery for make
pacman -Syyu # upgrade to latest software
# some of the below packages may be unneeded
pacman -S --needed mingw-w64-x86_64-xapian-core git base-devel mingw-w64-x86_64-toolchain # install needed tools
mkdir ~/.emacs.d
cd ~/.emacs.d
git clone https://github.com/casouri/xeft.git /opt/xeft 
cd xeft
g++ -o xapian-lite.dll -shared -fPIC -I/mingw64/include -L/mingw64/include -lxapian -lWs2_32 -municode # build xeft
# add activation for xeft to init.el
# launch emacs then xeft with "M-x  xeft [RET]"
```

**Emacs `init.el`**:

``` lisp
(add-to-list 'load-path "~/.emacs.d/xeft")
(require 'xeft)
; xeft-database
; xeft-directory
; xeft-default-extension
; xeft-recursive
```

**Comment by mcrosson** [comment]
I have also tried the below changes to the code to try to force-export the `plugin_is_GPL_compatible` but I still receive the compatibility error.

``` c++
nano -w module/xapian-lite.cc
    Change: int plugin_is_GPL_compatible;
    To: __declspec(dllexport) int plugin_is_GPL_compatible;
    
    Change:
        int
        emacs_module_init(struct emacs_runtime *ert)
    To:
        int __declspec(dllexport)
        emacs_module_init(struct emacs_runtime *ert)
```

**Comment by pRot0ta1p** [comment]
> I'm not sure if its because I didn't pull the 11.x g++ or not and I'm 100% not sure how to get msys2 to install concurrent versions of g++ so I can use an older version.

I don't think Msys2 can have concurrent version fo g++, its rolling release-ish kinda like archlinux.
Though I don't think older version of gcc is the problem either, the build proccess work back then.

In terms of your build proccess, I don't quite understand why you need to export PATH variable and call g++ manually instead of just invoke `make`. As long as you use the MinGW x64 environmet provided by msys2 (the blue icon one) there is no need to export PATH.

**Comment by mcrosson** [comment]
`mysy2 mingw x64 (blue icon)`

well that is a new way of launching mysy2. I'll try that and report back soon. Thank you for the tip.

**Comment by mcrosson** [comment]
With the patch at https://github.com/casouri/xeft/issues/11#issuecomment-1225074440 I can run the below procedure to compile and use xeft inside msys2. The compiled dll won't work outside msys2 and trying to compile statically had a compile error. Not sure if this is worth exploring, I wouldn't mind using native emacs on Windows with xeft ;)

```
# run mysy2 to install needed software
pacman -Syyu # upgrade to latest software
# some of the below packages may be unneeded
pacman -S --needed mingw-w64-x86_64-xapian-core git base-devel mingw-w64-x86_64-toolchain # install needed tools
# run mysy2 mingw x64 (blue icon) for build -- THIS IS CRITICAL
mkdir ~/.emacs.d
cd ~/.emacs.d
git clone https://github.com/casouri/xeft.git
cd xeft
make
# add activation for xeft to init.el
# launch emacs then xeft with "M-x  xeft [RET]"
```

**Comment by mcrosson** [comment]
You can also auto run the msys2 mingw emacs directly from a windows shortcut (these can be pinned to the taskbar) using the below.

`C:\msys64\usr\bin\mintty.exe -w hide /bin/env MSYSTEM=MINGW64 /bin/bash -l -i -c /mingw64/bin/runemacs.exe`

It'll launch using the `~/.emacs.d` directory in your msys2 home directory and once it launches it'll have full access to `C:`. You can even use chemacs2 or similar with profiles stored in `C:` that are auto loaded by chemacs2 profiles.

**Comment by casouri** [comment]
Ah, yes, duh. I fixed the makefile. IIUC that's the only thing that needs fixing right?

**Comment by pRot0ta1p** [comment]
Yes, issue solved confirmed , thank you.

**Comment by mcrosson** [comment]
> Ah, yes, duh. I fixed the makefile. IIUC that's the only thing that needs fixing right?

the instructions i added to the ticket may be good for windows userts ; or at least knowing to use the flavor of mingw noted above and the msys2 package thatll get you a native emacs ui ; these ended up being really important things for me to start using xeft.

Good stuff too btw ; this does what I wanted 💯

**Comment by pRot0ta1p** [comment]
I'll draft a PR on the windows instruction stuff later, I run emacs master branch in msys2 on windows as daily.

**Comment by panmengguan** [comment]
> With the patch at [#11 (comment)](https://github.com/casouri/xeft/issues/11#issuecomment-1225074440) I can run the below procedure to compile and use xeft inside msys2. ~The compiled dll won't work outside msys2 and trying to compile statically had a compile error. Not sure if this is worth exploring, I wouldn't mind using native emacs on Windows with xeft ;)~
> 
> If you install the `mingw-w64-x86_64-emacs` package you can invoke `runemacs` from within the `mysy2 mingw x64 (blue icon)` flavor of msys2 with a native ui.
> 
> ```
> # run mysy2 to install needed software
> pacman -Syyu # upgrade to latest software
> # some of the below packages may be unneeded
> pacman -S --needed mingw-w64-x86_64-xapian-core git base-devel mingw-w64-x86_64-toolchain # install needed tools
> # run mysy2 mingw x64 (blue icon) for build -- THIS IS CRITICAL
> mkdir ~/.emacs.d
> cd ~/.emacs.d
> git clone https://github.com/casouri/xeft.git
> cd xeft
> make
> # add activation for xeft to init.el
> # launch emacs then xeft with "M-x  xeft [RET]"
> ```

Does this solution only suitable for emacs installed from mingw? I use the native emacs binary from GNU Emacs mirror and follow this instruction. However, although the xapian-lite.dll has been properly generated, when I execute `M-x xeft`, there is the following error:

`xeft--require-xapian-lite: Module could not be opened: "c:/Users/xxx/.emacs.d/elpa/xeft-3.2/xapian-lite.dll"`

**Comment by TomoeMami** [comment]
I extracted `libxapian-30.dll` and compiled `xapian-lite.dll` for [kiennq's emacs build](https://github.com/kiennq/emacs-build). Just put it in the `path/to/your/xeft-*.*/`.

[kiennq-xeft.zip](https://github.com/user-attachments/files/19508505/kiennq-xeft.zip)

**Comment by TomoeMami** [comment]
Bump version

[kiennq-xeft.zip](https://github.com/user-attachments/files/19821702/kiennq-xeft.zip)

**Comment by TomoeMami** [comment]
Bump version

[kiennq-xeft.zip](https://github.com/user-attachments/files/20075816/kiennq-xeft.zip)

**Comment by casouri** [comment]
Thank you very much! Do you mind if I add it to the release? How should Windows users use the dll files? Do they simply move the files under any directory in `load-path`?

**Comment by TomoeMami** [comment]
> Thank you very much! Do you mind if I add it to the release?

https://github.com/casouri/xeft/pull/43

PR ceated.

**Comment by casouri** [comment]
Thanks for the PR! It's great! Though I just realized that this is the xeft repo. Do you mind opening a PR at the https://github.com/casouri/xapian-lite repo? Then I can add the windows binary to the release: https://github.com/casouri/xapian-lite/releases/tag/v2.1.0

Once we have all the binaries in the release, I can update the download link in xeft.el so people can download the binary directly from Emacs, if they so choose.

**Comment by TomoeMami** [comment]
https://github.com/casouri/xapian-lite/pull/4

PR created.

**Comment by casouri** [comment]
Thanks @TomoeMami! I updated the xapian-lite release and updated the pre-built binary URLs in xeft.el. I have one more favor to ask from you: could you try downloading the binary using `(xeft--download-module)` and see if the downloaded binary can be loaded by Emacs correctly?

**Comment by TomoeMami** [comment]
Something strange is happening.

1. Automatic download the `dlls` and press`M-x xeft` shows an error:

> if: Module could not be opened: "c:/Users/riko/AppData/Roaming/.emacs.d/elpa/packages/xeft-3.6.0.20250501.222827/xapian-lite.dll", "%1 不是有效的 Win32 应用程序。"

If I put them in custom `load-path`, it stills shows the same error.

2. If I manually download and rename the `DLLs` from release, put them in xeft's package directory, the `M-x xeft` shows an error:

> if: Module could not be opened: "c:/Users/riko/AppData/Roaming/.emacs.d/elpa/packages/xeft-3.6.0.20250501.222827/xapian-lite.dll", "找不到指定的模块。"

![Image](https://github.com/user-attachments/assets/e2a4772b-4cf8-4990-8bcc-4d8bd4e58851)

3. If I manually download and rename the `DLLs` from release, put them in a custom `load-path` like `~/.emacs.d/bin/`, they load correctly. 

![Image](https://github.com/user-attachments/assets/b4f3597d-90e2-4adc-b6c6-ea3f2ce597bc)

**Comment by TomoeMami** [comment]
Btw, I use [with-proxy](https://github.com/twlz0ne/with-proxy.el) with `xeft--download-module` to download files from GitHub inside emacs.

**Comment by casouri** [comment]
Well, I'm terribly sorry for the delay. Things got in the way :(

I might have messed up the object files when moving them around in Mac? I'll try to find some time and resolve it. Thanks again for all the trouble!
