### ISSUE TITLE
how to exclude a given directory

### ISSUE THREAD

**Issue by emacsbliss** [casouri/xeft#12]
Thanks for the package!

I just tried it with my notes directory which is under git version control, it turned out xeft generated quite big index (around 400Mb) even though my notes takes about 22Mb in space total.

I think it indexes the .git directory as well, is there anyway to exclude certain directory when ~xeft-recursive~ is set to t?

**Comment by casouri** [comment]
Completely untested, but now xeft should ignore dot-directories. If you want more fancy filtering you can customize `xeft-file-list-function`.

**Comment by emacsbliss** [comment]
Thanks a lot for quickly updating it!
