### ISSUE TITLE
xapian didn't support long file path

### ISSUE THREAD

**Issue by suliveevil** [casouri/xeft#15]
```emacs-lisp
 (xapian-lite-lib-error "InvalidArgumentError: Term too long (> 245): Q/Users/suliveevil/Documents/GitHub/Chaos/000图书-中图法/A马克思主义、列宁主义、毛泽东思想、邓小平理论/MaoZeDongAnthology/articles/中共发言人关于命令国民党反动政府重新逮捕前日本侵华军总司令冈村宁次和逮捕国民党内战罪犯的谈话.md")
```

**Comment by casouri** [comment]
Ah, this is a limitation of xapian's terms. I can fix this.

**Comment by suliveevil** [comment]
Thank you very much.

**Comment by casouri** [comment]
Ok, I updated xapian-lite and xeft. If you pull xeft and make clean; make, and remove the current database (`xeft-database`), and restart Emacs, xeft should be able to handle long file paths.

**Comment by suliveevil** [comment]
Works like magic!
