### ISSUE TITLE
How to use xeft-file-list-function correctly?

### ISSUE THREAD

**Issue by alon1996** [casouri/xeft#19]
Hello! Thanks for you contribution.

I have `xeft-directory` like "~/Dropbox/org", and there are some subdirectories under "org", like "book" "paper"...

How to use `xeft-file-list-function` for hide the contents of a folder "book"?

**Comment by alon1996** [comment]
By the way, how do i config it that open candidate file in second windows? Is `xeft--preview-file` this function?How should I configure it correctly?

**Comment by casouri** [comment]
Something like this (untested):
```
(defun my-xeft-file-list ()
  (let* ((dir-filter (lambda (file)
                       (not (file-regular-p file))))
         (file-filter (lambda (file)
                        (and (file-regular-p file)
                             (not (member (file-name-extension file)
                                          xeft-ignore-extension)))))
         (dir-list (seq-filter dir-filter
                               (directory-files xeft-directory t nil t))))
    (seq-filter file-filter
                (mapcar (lambda (dir)
                          (directory-files-recursively dir "\\`[^.]"))
                        (seq-difference dir-list '("book"))))))
```

**Comment by casouri** [comment]
By default SPC opens the preview. You can bind something else to `push-button`.
