### ISSUE TITLE
xeft-internal.h: No such file or directory

### ISSUE THREAD

**Issue by natrys** [casouri/xeft#2]
Hey, pretty cool demo. I am a `notdeft` user so would love to try this.

Currently I can't compile though (on linux):

```
$ make PREFIX=/usr
g++ -c -fPIC -I/usr/include -L/usr/lib -lxapian xeft-internal.cc -o xeft-internal.o
gcc -shared -fPIC -I/usr/include -L/usr/lib -lxapian xeft-module.c -o xeft-module.so
xeft-module.c:2:10: fatal error: xeft-internal.h: No such file or directory
    2 | #include "xeft-internal.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:11: xeft-module.so] Error 1
```

But that header file isn't part of the repo, so I am confused as to how to proceed.

**Comment by casouri** [comment]
Hi, I would pull the latest code and try again. I'm still not quite sure if this compiles on Linux, but my Linux server seems to be able to compile it with no problem.

**Comment by natrys** [comment]
It worked now! I cloned yesterday and apparently did some things which was causing subsequent `git pull` to fail, all the while I was thinking I was on latest commit.
