### ISSUE TITLE
backup usage

### ISSUE THREAD

**Issue by gitrj95** [casouri/xeft#20]
it's sort of tedious that xeft does not, either by default or by configuration, ignore emacs backup files. namely, the specification of xeft-ignore-extension to quoted ~ does not ignore the "extension" as the implementation uses file-name-extension, which ignores trailing ~ by default. it would be nice if you had some interface for ignoring these. i leave the design of this and its configurability to you -- if you think these semantics would be useful

**Comment by casouri** [comment]
I added `xeft-file-filter` and `xeft-directory-filter`, they should be enough for any kind of filtering: whitelist, blacklist, regexp, etc.

**Comment by gitrj95** [comment]
sounds reasonable. looking forward to the elpa release

**Comment by casouri** [comment]
A new version is released on ELPA.

**Comment by gitrj95** [comment]
do these filters respect search queries? it seems if i search something that's excluded from indexing by these filters, they show up again in the gun

**Comment by casouri** [comment]
Did you delete the database and let xeft reindex? Because files already in the database are not automatically removed.

**Comment by gitrj95** [comment]
ah does C-c C-R not do this? didn't check the implementation. i'll try this and get back to you

**Comment by casouri** [comment]
It reindex all the files but doesn't delete the database, ie, doesn't remove files you don't want but are indexed before using the filter functions. So you need to delete the database folder on disk and reopen xeft. I'll make the docstring of the filter functions more explicit about this. Thanks!

**Comment by gitrj95** [comment]
looks good. thanks
