### ISSUE TITLE
Show file name in xeft buffer

### ISSUE THREAD

**Issue by panmengguan** [casouri/xeft#22]
Thanks for the package!

Is it possible to show the file names in the xeft searching buffer? Some of my org-mode files have other information in the first line rather than the title, which makes it unclear where the search results come from.

Thanks.

**Comment by casouri** [comment]
Oops, I missed this one, sorry about that. You can achieve that by

```
(setq xeft-title-function #'file-name-nondirectory)
```

**Comment by panmengguan** [comment]
Solved. Thanks!
