### ISSUE TITLE
Show preview for all files as one goes through each one

### ISSUE THREAD

**Issue by rdiaz02** [casouri/xeft#23]
Thanks a lot for the package. Fast and intuitive to use. :-)

Would it be possible to enable a setting such that:
1. The file is always previewed
2. Ideally, as one moves to the next file that buffer is removed (so as not to fill the buffer list with files).

**Comment by casouri** [comment]
Try this:

```
(defvar-local xeft--displayed-by-xeft-p nil)

(defun xeft--preview-when-highlight ()
  (when-let* ((button (button-at (point)))
              (path (button-get button 'path)))
    ;; Kill previously displayed buffer.
    (when (window-live-p xeft--preview-window)
      (with-selected-window xeft--preview-window
        (when xeft--displayed-by-xeft-p
          (kill-buffer))))
    ;; Show preview of current selection.
    (xeft--preview-file path)))

(add-hook 'xeft-find-file-hook
          (lambda () (setq xeft--displayed-by-xeft-p t)))

(advice-add 'xeft--highlight-file-at-point
            :after #'xeft--preview-when-highlight)
```

**Comment by rdiaz02** [comment]
That works great!  Thanks a lot!!

**Comment by rdiaz02** [comment]
Would it be worth making this explicit in the README? If you think it is a good idea, I can make a pull request with additions to the README.

**Comment by casouri** [comment]
That might be a good idea. I can add a FAQ section in the README. I'll spare you from the work since I know some other nice materials to add from other issues ;-)

**Comment by rdiaz02** [comment]
;-)  Perfect, thanks a lot!
