### ISSUE TITLE
some extensions are not ignored, and some non-ignored extensions are ignored

### ISSUE THREAD

**Issue by rdiaz02** [casouri/xeft#24]
Some entries en `xeft-ignore-extension` are ignored (and other extensions not in that variable are ignored).

Minimal reproducible example

```
(package-initialize)
(add-to-list 'load-path "~/Sources/xeft")
(setq xeft-directory "~/tmp2")
(setq xeft-database "~/.deft/db")
(setq xeft-ignore-extension '("txt~" "tat" "org~"))
(setq xeft-default-extension "txt")

(require 'xeft)
```

Now, create the `xeft-directory` and add only these files as follows:

```
echo aaaaa1 > f1.org~
echo bbbbb2 > f2.txt~
echo ccccc3 > f3.tat
echo ddddd4 > f4.tat~
echo eeeee5 > f5.uuu
echo fffff6 > f6.org
echo ggggg7 > f7.txt
```

xeft shows:

```
aaaaa1  # should not be here, as it is coming from a org~ file
bbbbb2  # should not be here, as it is coming from a txt~ file
eeeee5 # OK
fffff6 # OK
ggggg7 # OK
```
 
But ddddd4 (which is in f4.tat~, a non-excluded extension) is not shown (ccccc3 is not shown, as it should).

The problem arises in line 709 to 710 of xeft.el: 
```
(not (member (file-name-extension file)
                    xeft-ignore-extension))))
```

because it uses `file-name-extension` which, as per documentation, "Return FILENAME’s final "extension" sans any backup version strings." We can check

```
(file-name-extension "cucu.org~")
```
returns `org` , not `org~`.

**Comment by casouri** [comment]
Xeft uses `file-name-extension` to get the extension of a file, interestingly, it removes "backup version strings" at the end of an extension. so all the "tat~", "txt~" etc becomes "tat", "txt" when xeft compares them to `xeft-ignore-extension`.

Perhaps it's better to inhibit this "back version" cleaning, hmm...

**Comment by rdiaz02** [comment]
Thanks for your reply. 

I assume most people will not want their backup files indexed. But I guess the ideal thing would be to allow using extensions without having the `~` removed. But this does not seem straightforward.

**Comment by rdiaz02** [comment]
How about changing the use of `file-name-extension` by this simple alternative:

```
(defun file-name-extension-no-rm-bckp (file)
  "Return FILENAME’s final \"extension\" without removing backup version strings."
  (substring
   (file-name-nondirectory file)
   (1+ (string-match "\\." (file-name-nondirectory file)))))
```

**Comment by rdiaz02** [comment]
This works for me.  Define `file-name-extension-no-rm-bckp` as

```
(defun file-name-extension-no-rm-bckp (filename &optional period)
  "Return FILENAME's final \"extension\" including backup version strings.
The extension, in a file name, is the part that begins with the last `.',
except that a leading `.' of the file name, if there is one, doesn't count.
This function is the same as `file-name-extension', except it does not call
`file-name-sans-versions' (the function responsible of removing
any parts that indicate backup versions and
version strings.
Return nil for extensionless file names such as `foo'.
Return the empty string for file names such as `foo.' that end in a period.

By default, the returned value excludes the period that starts the
extension, but if the optional argument PERIOD is non-nil, the period
is included in the value, and in that case, if FILENAME has no
extension, the value is \"\"."
  (save-match-data
    (let ((file  (file-name-nondirectory filename)))
      (if (and (string-match "\\.[^.]*\\'" file)
	       (not (eq 0 (match-beginning 0))))
          (substring file (+ (match-beginning 0) (if period 0 1)))
	(if period
	    "")))))
```

and, then, in ` xeft-default-file-filter `, instead of  `(not (member (file-name-extension file) ` we have `(not (member (file-name-extension-no-rm-bckp file)`.

**Comment by casouri** [comment]
Thanks, I thought about this a bit and it's probably more intuitive if we don't remove the "version strings", so I added a function like you suggested.

**Comment by rdiaz02** [comment]
Thanks a lot!!! Closing the issue as fixed.
