### ISSUE TITLE
-<token> does not work

### ISSUE THREAD

**Issue by gitrj95** [casouri/xeft#26]
- m1 mbp
- compiling xapian against /opt/homebrew
- claims compiled successfully
- search doesn't work

**Comment by casouri** [comment]
What do you mean by -<token>?

**Comment by gitrj95** [comment]
when in xeft, if i type -apple, i expect all notes expect apple in the text right? instead, i just get notes with apple in them

**Comment by casouri** [comment]
I guess you need to add at least one other query term, like `fruit -apple`, to make the negative sign take effect.

**Comment by gitrj95** [comment]
hmm. not a fan of that, but i guess that's just how the engine works? won't bother looking further, then

**Comment by casouri** [comment]
Xeft uses Xapian for indexing and searching, their documentation isn't super clear on this so I don't know.
