### ISSUE TITLE
Could xeft support arm64?

### ISSUE THREAD

**Issue by Prague2049** [casouri/xeft#28]
When I install Xeft, it needs the dynamic module to work. However  it gives error like below?

xapian-lite.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))"

**Comment by casouri** [comment]
I'm guessing that you are on an M1 Macbook, and tried to use the prebuilt xapian-lite, which is built for x86_64. You'll need to build xapian-lite locally. There's a section in the README that describe how to do it.

**Comment by Prague2049** [comment]
1.There are info for xeft compile:
c++ xapian-lite.cc -o xapian-lite.dylib -shared -fPIC -I/opt/homebrew/Cellar/xapian/1.4.21/include -std=c++11 -L/opt/homebrew/Cellar/xapian/1.4.21/lib -lxapian
In file included from xapian-lite.cc:43:
./emacs-module-prelude.h:149:1: warning: mangled name of 'emp_define_function' will change in C++17 due to non-throwing exception specification in function signature [-Wc++17-compat-mangling]
emp_define_function
^
1 warning generated.
In the message buffer, I get feedback like:
Successfully compiled the module :-D
When I use M+x xeft, the expected interface does not appear?
<img width="478" alt="image" src="https://github.com/casouri/xeft/assets/86907530/ebbccfa3-5a08-456b-9613-bccab3bdbd2a">

**Comment by casouri** [comment]
The compilation is successful. No errors or other messages? What do you get if you evaluate `(require 'xapian-lite)`? Have you tried restarting Emacs?

**Comment by Prague2049** [comment]
Yes! I also add (require 'xapian-lite) in the init.el file. However I don't get the expected result.

**Comment by casouri** [comment]
So `(require 'xapian-lite)` doesn't error either? I can't think of a reason why you are not seeing anything :-(

**Comment by Nathan-Furnal** [comment]
I built it locally with no issues on M2, just had to use `/opt/hombrew` as the PREFIX.

**Comment by Prague2049** [comment]
Could you share your xapian-lite.dylib files?

**Comment by casouri** [comment]
Actually, do you have any notes in the xeft directory? What happens if you type a few words on the first line? I just realized that a blank page is what you'll see if there's no notes. (I should change that.)

**Comment by Prague2049** [comment]
Thanks a lot!!! Closing the issue as fixed.
