### ISSUE TITLE
Module could not be opened

### ISSUE THREAD

**Issue by adouzzy** [casouri/xeft#3]
Emacs on latest Master branch.
I can load the package fine. I can build the module fine. No errors.
When I run M-x xeft, I have the following error
```
if: Module could not be opened: "/home/xxx/.emacs.d/opt/xeft/xeft-module.so", "/home/xxx/.emacs.d/opt/xeft/xeft-module.so\
: undefined symbol: _ZN6Xapian16WritableDatabaseD1Ev"Unable to load color "light golenrod"
```

**Comment by casouri** [comment]
That's strange, seems that OS cannot find symbols in Xapian dylib. What compiler did you use to build Xeft, and what compiler is used to build/install Xapian?

**Comment by casouri** [comment]
Looks it has to do with linking. Try the latest commit and compile xeft again, it should be able to find xapian symbols now.

**Comment by adouzzy** [comment]
Error gone. Thanks! :taco:
