### ISSUE TITLE
xeft not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by fapdash** [casouri/xeft#33]
First of all: I love your package, thank you very much. It helps me alot.

Sadly I can't get xeft to run on Ubuntu 24.04.
I'm not very familiar with the C build system. Can you please help me?

When I download the prebuilt binary I get th error:

```
(module-open-failed "/home/fap/.emacs.d/elpa/xeft-3.3/xapian-lite.so" "/snap/emacs/2504/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/fap/.emacs.d/elpa/xeft-3.3/xapian-lite.so)")
```

When I try to build locally (had to install `libxapian-dev`) I get the error:
```
(module-open-failed "/home/fap/.emacs.d/elpa/xeft-3.3/xapian-lite.so" "/snap/emacs/2504/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/fap/.emacs.d/elpa/xeft-3.3/xapian-lite.so)")
```

Ubuntu 24.04 comes with glibc 2.39:

```
$ ldd --version
ldd (Ubuntu GLIBC 2.39-0ubuntu8.2) 2.39
```

**Comment by casouri** [comment]
Hmm, I'm not an expert either, but it seems to have something to do with snap: snap bundles a glibc with your Emacs together, and that glibc's version is 2.38. Where as the global glibc on your system is at 2.39.

You can try either installing Emacs through apt, or building xeft with glibc 2.38.

**Comment by fapdash** [comment]
Fixed in https://github.com/casouri/xeft/commit/9ee7d6026cb79ebec440109329911c2510710c2a and https://github.com/casouri/xeft/commit/924d0c9bc2b6a666a3819447172c9139561ae209, closing.
