### ISSUE TITLE
Ignored files are not kept after searches

### ISSUE THREAD

**Issue by Nathan-Furnal** [casouri/xeft#5]
Hi again, 

I think the ignored files are only ignored when `xeft` is first called but not afterwards. 

For example, create a directory with one accepted file `test.txt` and another ignored file like `test.log`. When you first run  `M-x xeft` then only `test.txt` will show up but if you type something in the search bar which matches both files then `test.log` will also show up!

**Comment by casouri** [comment]
Did you change the value of `xeft-ignore-extension` after the database is created? In that case, since the database has already indexed the files, they will appear when you search. If you don't want to see those files, simply delete the database and start xeft again.

**Comment by Nathan-Furnal** [comment]
Fair enough, thanks for the help!

**Comment by casouri** [comment]
Thanks for reporting. I've updated the documentation for `xeft-ignore-extension` to explain that quirk ;-)

**Comment by Nathan-Furnal** [comment]
Good stuff! One improvement I could see being useful though is have a list of allowed files extensions rather than a exclusion list. Right now I export org files to LaTeX and then PDF, which generates a lot of intermediate files I have to ignore. Which is for example the choice deft makes with [deft extensions](https://github.com/jrblevin/deft/blob/master/deft.el#L566).
