### ISSUE TITLE
Is there an intent to make it reads a directory recursively?

### ISSUE THREAD

**Issue by tareefdev** [casouri/xeft#6]
Thanks for the efforts here. Can we have an option like this in deft 
`(setq deft-recursive t)`

**Comment by casouri** [comment]
Not planned, but since you asked, I added it. I didn't test for it, could you please give it a try? Thanks.

**Comment by tareefdev** [comment]
Thanks a lot for your great resoponse. I'm getting the following error while trying to run xeft:
`let: Xapian error: "InvalidArgumentError: Term too long (> 245): Q/home/tareef/org/data/30/a6e74a-3bf3-46ad-a402-6a6aa60f8a5d/2020-01-13T21:04:31+0300/www.suse.com/min/index.html?b=assets%2Fcss&f=bootstrap.css,helpers.css,jquery-ui.min.css,featherlight.min.css,featherlight.gallery.min.css,lightslider.css,main.css,iefix.css"`
I think xeft should only read org files, right? I have some other files inside my org dir

**Comment by casouri** [comment]
Xeft reads every text file. If you want to exclude some files, use `xeft-ignore-extension`.

**Comment by wakatara** [comment]
The recursive feature works great for most directories, but I do have a symlink in one of my directories and it appears not to index the files that are symlinked there (it's a symlink to have my blog posts work under org-roam with md-roam. See directory tree below. 

One thing to note, the main directory is actually on an iCoud drive (but indexes fine) and the `ln -s` is to an actual directory on the SSD, so not sure if that makes a difference. 
OSX 13.1 Ventura, emacs 29.0.60.

```bash
.
├── archives
├── areas
│   ├── blog -> /Users/daryl/Code/daryl.wakatara.com/content/posts
│   ├── dh
│   ├── exps
│   ├── goals
│   ├── learn
│   └── loka
├── journal
├── logs
├── projects
└── refs
    ├── assets
    ├── astro
    ├── images
    ├── prm
    ├── rez
    └── templates
```

**Comment by casouri** [comment]
Xeft doens't follow symlinks by default. I added a new possible value to `xeft-recursive`, now if you set it to `follow-symlinks`, xeft will follow symlinks.
