### ISSUE TITLE
Prefer allowed extensions over ignored extensions

### ISSUE THREAD

**Issue by Nathan-Furnal** [casouri/xeft#7]
Hi casouri, 

I'd like to modify the behavior of the ignored extensions and rather prefer allowed extensions. I think it'll be easier to use because it helps filter out the noise rather than picking out all the ignored extensions. For example, I convert files through LaTeX which generates a lot of intermediate files which I don't need. This is the behavior I'd implement instead : 

```elisp 

(defcustom xeft-allowed-extension '("txt")
  "Files with extensions in this list are allowed.
All other files are ignored."
  :type '(list string))
```
It requires only a small change in the function `xef--file-list`, like so : 

```elisp
(defun xeft--file-list ()
  "Return a list of all files in ‘xeft-directory’."
  (cl-remove-if-not
   (lambda (file)
     (and (file-regular-p file)
          (not (string-prefix-p
                "." (file-name-base file)))
          (member (file-name-extension file)
                  xeft-allowed-extension)))
   (directory-files xeft-directory t nil t)))
```

Finally, every extension is is specified without a dot beforehand, like `"txt"` except for the `xeft-default-extension` which defaults to `".txt"`, I think it would be more consistent to use this instead : 

```elisp
(defcustom xeft-default-extension "txt"
  "The default extension for new files created by xeft."
  :type 'string)

(defcustom xeft-filename-fn
  (lambda (search-phrase)
    (concat search-phrase "." xeft-default-extension))
  "A function that takes the search phrase and returns a filename."
  :type 'function)
``` 

Cheers =)

**Comment by casouri** [comment]
I think it comes down to personal preference, as both approach has their advantages. I like the inclusiveness of the current logic: the user can use whatever extension he pleases and don't need to customize anything. The convenience of ignoring intermediate files doesn't over-weight that inclusiveness for me. I applied your change to make extensions more uniform, thanks :-)

**Comment by Nathan-Furnal** [comment]
We'll have to agree to disagree on this one I guess, I find it easier to manage what I'm seeing with an allowed list and I find it helps filtering out stray files!
