### ISSUE TITLE
Publish to MELPA

### ISSUE THREAD

**Issue by Nathan-Furnal** [casouri/xeft#9]
Hi casouri, I'd like to know if it were possible to publish the package to [MELPA](https://github.com/melpa/melpa/blob/master/README.md)? I've never done so but I'd like to help build the recipe if possible. What do you think?

**Comment by casouri** [comment]
I would consider that if it is really needed, ie, enough people wanting to use it and want it on MELPA. As far as I can see, currently only you and me and a few others are using xeft and I don't see the need for it. (Plus I was hoping that people would integrate xeft-module into their tool, and xeft is just my personal note tool / demo for xeft-module.)

**Comment by Nathan-Furnal** [comment]
I like xeft very much, it fixed all the speed issues I had with deft, I think others could benefit as well. What do you have in mind for a tool build upon xeft?

**Comment by casouri** [comment]
Thank you :-) I'm thinking about modifying Deft to optionally utilize xeft-module. Deft is much more mature it has been used for years and has added customize options to fit everyone's need. Come to think of it, Xeft is really "yet another Deft" and it might not be a good idea to publish it.

**Comment by Nathan-Furnal** [comment]
That's fair, a "xeft'd" deft would great!

**Comment by casouri** [comment]
Indeed, though somebody needs to make it happen ;-)

**Comment by Nathan-Furnal** [comment]
I'll learn more about C/C++ in the coming months, I'll take a look then =) My elisp is also pretty poor so that's something to work on as well. Still, I think your implementation is valuable and would benefit most deft users.

**Comment by casouri** [comment]
You don't need to know C/C++ to use xeft-module. Just `(require 'xeft-module)` and use `xeft-reindex-file` and `deft-query-term`. You can have a look at the README for an example.

**Comment by Nathan-Furnal** [comment]
Nice, that makes it easier!

**Comment by casouri** [comment]
I had some free time and added xapian support to deft: https://github.com/jrblevin/deft/issues/110

**Comment by Nathan-Furnal** [comment]
Pretty cool! I'm still using `xeft` exclusively though, it's minimal and just what I need =)

**Comment by casouri** [comment]
Glad you like it ;-)
